services:
  - type: web
    name: wordpress-app
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    autoDeploy: true
    envVars:
      - key: WORDPRESS_DB_HOST
        fromDatabase:
          name: wp-db
          property: host
      - key: WORDPRESS_DB_USER
        fromDatabase:
          name: wp-db
          property: user
      - key: WORDPRESS_DB_PASSWORD
        fromDatabase:
          name: wp-db
          property: password
      - key: WORDPRESS_DB_NAME
        fromDatabase:
          name: wp-db
          property: database

databases:
  - name: wp-db
    plan: starter
    region: oregon
    databaseName: wordpress
    user: wpuser
